modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/MaxNeedsSnacks/roadrunner/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "roadrunner"
version = "${version}"
displayName = "RoadRunner"
logoFile = "icon.png"
description = '''
An unofficial fork of the popular optimisation mod Lithium, made for the Forge mod loader.
'''
credits = "JellySquid, 2No2Name"
authors = "embeddedt, dima_dencep, NanoLive"
displayURL = "https://curseforge.com/minecraft/mc-mods/roadrunner"
provides=["lithium"]
